version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped

    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel

    ports:
     - '3000:3000'

    volumes:
     - './data:/var/lib/grafana'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped

    ports:
     - '9090:9090'

    volumes:
     - './prometheus.yml:/etc/prometheus/prometheus.yml'

  test-host:
    image: alpine:latest
    container_name: test-host
    restart: unless-stopped
    build:
      context: ./test-host
      dockerfile: ./Dockerfile
    ports:
     - '9100:9100'
